version: "2"
services:
  backend:
    image: streampipes/backend:${SP_BACKEND_VERSION}
    depends_on:
      - consul
      - couchdb
    ports:
      - "8030:8030"
    environment:
      - SP_KAFKA_HOST=${SP_KAFKA_HOST}
    volumes:
      - ./config:/root/.streampipes
      - ./config/RDF4J:/root/.RDF4J
    networks:
      spnet:

