version: "2"
services:
  connect-master:
    image: streampipes/streampipes-connect-container:${SP_BACKEND_VERSION}
    depends_on:
      - consul
      - couchdb
      - connect-worker
    ports:
      - "8099:8099"
    environment:
      - EXECUTION_MODE=MASTER
      - SP_CONNECT_CONTAINER_HOST=connect-master      
      - SP_CONNECT_CONTAINER_WORKER=connect-worker
      - SP_KAFKA_HOST=${SP_KAFKA_HOST}
    networks:
      spnet:

