version: "2"
services:
  nginx:
    image: streampipes/ui:0.60.1
    ports:
      - "80:80"
    depends_on:
      - couchdb
      - activemq
      - consul
      - swagger-ui
      - connect-master
      - backend
    networks:
      spnet:
 
