version: "2"
services:
  sources-watertank-simulator:
    image: streampipes/sources-watertank-simulator:${SP_PE_VERSION}
    depends_on:
      - "consul"
#    ports:
#      - "8098:8090"
    environment:
      - SP_ICON_HOST=${SP_ICON_HOST}
      - SP_KAFKA_HOST=${SP_KAFKA_HOST}
    networks:
      spnet:

